name: PR-sanity-check
on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup Node.js environment
      uses: actions/setup-node@v1.4.3

    - name: install deps
      run: yarn

    - name: lint checks
      run: yarn lint

    - name: unit tests
      run: yarn test
